services:
  calibre-web:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    #    ports:
    #      - "8083:8083"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${BASE_PATH}/calibre-web/config:/config"
      - "${BASE_PATH}/data/media/books/books:/calibre-library"
      - "${BASE_PATH}/data/media/books/books-ingest:/cwa-book-ingest" # Ingest Books

networks:
  proxy:
    external: true
