services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - .env
    ports:
      # Puertos DNS (Obligatorios)
      - "53:53/tcp"
      - "53:53/udp"
      # Puerto HTTP para el panel web
      #      - "8090:80/tcp"
      #      # Puerto HTTPS
      - "8443:443/tcp"
    environment:
      # 1. ZONA HORARIA: Configurada para tu ubicación en Hidalgo, México.
      TZ: ${TZ}

      # 2. CONTRASEÑA: Cambia la pass dentro del .env por una contraseña segura tuya.
      FTLCONF_webserver_api_password: ${INITIAL_PASSWORD}

      # Modo de escucha DNS para Docker
      FTLCONF_dns_listeningMode: 'ALL'

      # Desactivar el límite de peticiones por culpa del NAT de Docker
      FTLCONF_rate_limit: '0/0'
    volumes:
      # Guarda la configuración y listas para que no se borren si reinicias el contenedor
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
