services:
  bindery:
    image: ghcr.io/vavallee/bindery:latest
    container_name: bindery
    restart: unless-stopped
    env_file:
      - ../.env
    user: "${PUID}:${PGID}"
    networks:
      - proxy
    # ports:
    #   - "8787:8787"
    environment:
      BINDERY_LOG_LEVEL: info
      BINDERY_PUID: ${PUID}
      BINDERY_PGID: ${PGID}
      TZ: ${TZ}
      BINDERY_DOWNLOAD_DIR: /data/torrents/books/books
      BINDERY_LIBRARY_DIR: /data/media/books/books
      BINDERY_AUDIOBOOK_DIR: /data/media/books/audiobooks
      BINDERY_AUDIOBOOK_DOWNLOAD_DIR: /data/torrents/books/audiobooks
    volumes:
      - "./config:/config"
      - "../data:/data"

networks:
  proxy:
    external: true
